# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/

name: Cortex-M

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on:
  schedule:
    - cron: '0 4 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  x86_tests_one:
    runs-on: ubuntu-latest

    name: Makefile x86 One(presubmit)
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.trigger-sha }}
      - name: Install dependencies
        run: |
          pip3 install Pillow
          pip3 install Wave
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_makefile.sh
          cd ../
          tflite-micro/tensorflow/lite/micro/tools/ci_build/test_x86_subset_1.sh tflite-micro/

  x86_tests_two:
    runs-on: ubuntu-latest

    name: Makefile x86 Two(presubmit)
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.trigger-sha }}
      - name: Install dependencies
        run: |
          pip3 install Pillow
          pip3 install Wave
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_makefile.sh
          cd ../
          tflite-micro/tensorflow/lite/micro/tools/ci_build/test_x86_subset_2.sh tflite-micro/

  cortex_m_bluepill:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro')

    name: Modified Cortex Test bluepill
    steps:
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install Pillow
          pip3 install Wave
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_bluepill.sh 


  cortex_m_stm32f4:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro')

    name: Modified Cortex Test bluepill
    steps:
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install Pillow
          pip3 install Wave
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_stm32f4.sh 

  issue-on-error:
    needs: [cortex_m_bluepill, cortex_m_stm32f4]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/issue_on_error.yml
    with:
      repo: ${{ github.repository }}
      workflow: ${{ github.workflow }}
      run_id: ${{ github.run_id }}
      run_number: ${{ github.run_number }}
      flag_label: ci:bot_issue
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
