name: Post Tests
# This is for tests that run on a PR post merge. This to optimize CI test suite time
# for exceptionally long running test processes. Errors will still generate an
# issue against the PR/commit so will be caught.

on:
  pull_request:
    types:
      - closed

jobs:
  hifimini_unit_tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    name: Hifimini Unit Tests (postmerge)
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.trigger-sha }}
      - run: |
          rm -rf .git
          echo ${{ secrets.tflm-bot-token }} | docker login ghcr.io -u tflm-bot --password-stdin
          docker run --env XTENSA_TOOLS_VERSION=RI-2019.2-linux --rm -v `pwd`:/opt/tflite-micro ghcr.io/tflm-bot/xtensa:0.4 \
          /bin/bash -c \
          "cd /opt && tflite-micro/tensorflow/lite/micro/tools/ci_build/test_xtensa_hifimini.sh tflite-micro/"
  
  issue_on_error:
    needs: hifimini_unit_tests
    if: ${{ failure() }}
    name: Error Handler
    env:
      REPO: ${{ github.repository}}
      WORKFLOW: ${{ github.workflow }}
      RUN_NUMBER: ${{ github.run_number }}
      RUN_ID: ${{ github.run_id }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FLAG_LABEL: ci:bot_issue
      PR_NUMBER: ${{ github.event.number }}
      PR_LINK: ${{github.event.pull_request._links.html.href}}
    run: |
      python3 ci/issue_on_error_post.py

