name: Post Tests
# This is for tests that run on a PR post merge. This to optimize CI test suite time
# for exceptionally long running test processes. Errors will still generate an
# issue against the PR/commit so will be caught.

on:
  pull_request:
    types:
      - closed

jobs:
  hifimini_unit_tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    name: Hifimini Unit Tests (postmerge)
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.trigger-sha }}
      - run: |
          rm -rf .git
          echo ${{ secrets.tflm-bot-token }} | docker login ghcr.io -u tflm-bot --password-stdin
          docker run --env XTENSA_TOOLS_VERSION=RI-2019.2-linux --rm -v `pwd`:/opt/tflite-micro ghcr.io/tflm-bot/xtensa:0.4 \
          /bin/bash -c \
          "cd /opt && tflite-micro/tensorflow/lite/micro/tools/ci_build/test_xtensa_hifimini.sh tflite-micro/"
  
  f1_unit_tests:
    runs-on: ubuntu-latest

    name: Fusion F1 Unit Tests (presubmit)
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.trigger-sha }}
      - run: |
          rm -rf .git
          echo ${{ secrets.tflm-bot-token }} | docker login ghcr.io -u tflm-bot --password-stdin
          docker run --env XTENSA_TOOLS_VERSION=RI-2020.4-linux --rm -v `pwd`:/opt/tflite-micro ghcr.io/tflm-bot/xtensa:0.4 \
          /bin/bash -c \
          "cd /opt && tflite-micro/tensorflow/lite/micro/tools/ci_build/test_xtensa_fusion_f1.sh EXTERNAL tflite-micro/"

  issue_on_error:
    needs: [hifimini_unit_tests, f1_unit_tests]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/issue_on_error.yml
    with:
      repo: ${{ github.repository}}
      workflow: ${{ github.workflow }}
      run_number: ${{ github.run_number }}
      run_id: ${{ github.run_id }}
      flag_label: ci:bot_issue
      pr_number: ${{ github.event.number }}
      pr_link: ${{ github.event.pull_request._links.html.href }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      
